apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: whisper
        image: your-username/whisper:latest
        resources:
          limits:
            nvidia.com/gpu: 1 # Request one GPU
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: Exists
